### ISSUE TITLE
[Linter] Warn user about capabilities stored inside public arrays or dictionaries

### ISSUE THREAD

**Issue by franklywatson** [onflow/cadence-tools#16] opened 2022-09-16 21:36 UTC
## Description

Ensure capabilities cannot be accessed by unauthorized parties. For example, capabilities should not be accessible through a public field, including public dictionaries or arrays. Exposing a capability in such a way allows anyone to borrow it and perform all actions that the capability allows. 

## Acceptance criteria 

* Linter issues a warning when capabilities are stored in public arrays or dictionaries
* Link to the guidance on what risks this poses

**Comment by SupunS** [comment] 2023-07-19 15:15
Duplicate of https://github.com/onflow/cadence-tools/issues/6

**Closed** 2023-07-31 18:35 UTC
Labels: SC-Eng, Good First Issue
